package com.sati.model;
// Generated 13 juin 2022 à 11:48:42 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etat generated by hbm2java
 */
@Entity
@Table(name = "etat", catalog = "ismistock_bd")
public class Etat implements java.io.Serializable {

	private int idEtat;
	private String codeEtat;
	private String libEtat;
	private Set<Diagnostique> diagnostiques = new HashSet<Diagnostique>(0);

	public Etat() {
	}

	public Etat(int idEtat) {
		this.idEtat = idEtat;
	}

	public Etat(int idEtat, String codeEtat, String libEtat, Set<Diagnostique> diagnostiques) {
		this.idEtat = idEtat;
		this.codeEtat = codeEtat;
		this.libEtat = libEtat;
		this.diagnostiques = diagnostiques;
	}

	@Id

	@Column(name = "ID_ETAT", unique = true, nullable = false)
	public int getIdEtat() {
		return this.idEtat;
	}

	public void setIdEtat(int idEtat) {
		this.idEtat = idEtat;
	}

	@Column(name = "CODE_ETAT", length = 10)
	public String getCodeEtat() {
		return this.codeEtat;
	}

	public void setCodeEtat(String codeEtat) {
		this.codeEtat = codeEtat;
	}

	@Column(name = "LIB_ETAT", length = 25)
	public String getLibEtat() {
		return this.libEtat;
	}

	public void setLibEtat(String libEtat) {
		this.libEtat = libEtat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etat")
	public Set<Diagnostique> getDiagnostiques() {
		return this.diagnostiques;
	}

	public void setDiagnostiques(Set<Diagnostique> diagnostiques) {
		this.diagnostiques = diagnostiques;
	}

}
