package com.sati.model;
// Generated 13 juin 2022 à 11:48:42 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAuthorization generated by hbm2java
 */
@Entity
@Table(name = "user_authorization", catalog = "ismistock_bd")
public class UserAuthorization implements java.io.Serializable {

	private int userRoleId;
	private UserAuthentication userAuthentication;
	private String role;

	public UserAuthorization() {
	}

	public UserAuthorization(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	public UserAuthorization(int userRoleId, UserAuthentication userAuthentication, String role) {
		this.userRoleId = userRoleId;
		this.userAuthentication = userAuthentication;
		this.role = role;
	}

	@Id

	@Column(name = "USER_ROLE_ID", unique = true, nullable = false)
	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public UserAuthentication getUserAuthentication() {
		return this.userAuthentication;
	}

	public void setUserAuthentication(UserAuthentication userAuthentication) {
		this.userAuthentication = userAuthentication;
	}

	@Column(name = "ROLE", length = 20)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
