package com.sati.model;
// Generated 18 mai 2022 à 07:58:28 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * EtatDemande generated by hbm2java
 */
@Entity
@Table(name = "etat_demande", catalog = "ismistock_bd")
public class EtatDemande implements java.io.Serializable {

	private int idEtatDemande;
	private String codeEtatDemande;
	private String libEtatDemande;
	private Set<Demande> demandes = new HashSet<Demande>(0);

	public EtatDemande() {
	}

	public EtatDemande(int idEtatDemande) {
		this.idEtatDemande = idEtatDemande;
	}

	public EtatDemande(int idEtatDemande, String codeEtatDemande, String libEtatDemande, Set<Demande> demandes) {
		this.idEtatDemande = idEtatDemande;
		this.codeEtatDemande = codeEtatDemande;
		this.libEtatDemande = libEtatDemande;
		this.demandes = demandes;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_ETAT_DEMANDE", unique = true, nullable = false)
	public int getIdEtatDemande() {
		return this.idEtatDemande;
	}

	public void setIdEtatDemande(int idEtatDemande) {
		this.idEtatDemande = idEtatDemande;
	}

	@Column(name = "CODE_ETAT_DEMANDE", length = 10)
	public String getCodeEtatDemande() {
		return this.codeEtatDemande;
	}

	public void setCodeEtatDemande(String codeEtatDemande) {
		this.codeEtatDemande = codeEtatDemande;
	}

	@Column(name = "LIB_ETAT_DEMANDE", length = 25)
	public String getLibEtatDemande() {
		return this.libEtatDemande;
	}

	public void setLibEtatDemande(String libEtatDemande) {
		this.libEtatDemande = libEtatDemande;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatDemande")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

}
