package com.sati.model;
// Generated 18 mai 2022 à 07:58:28 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Famille generated by hbm2java
 */
@Entity
@Table(name = "famille", catalog = "ismistock_bd")
public class Famille implements java.io.Serializable {

	private int idFamille;
	private String codeFamille;
	private String libFamille;
	private String descriptionFamille;
	private Set<Materiel> materiels = new HashSet<Materiel>(0);

	public Famille() {
	}

	public Famille(int idFamille) {
		this.idFamille = idFamille;
	}

	public Famille(int idFamille, String codeFamille, String libFamille, String descriptionFamille,
			Set<Materiel> materiels) {
		this.idFamille = idFamille;
		this.codeFamille = codeFamille;
		this.libFamille = libFamille;
		this.descriptionFamille = descriptionFamille;
		this.materiels = materiels;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_FAMILLE", unique = true, nullable = false)
	public int getIdFamille() {
		return this.idFamille;
	}

	public void setIdFamille(int idFamille) {
		this.idFamille = idFamille;
	}

	@Column(name = "CODE_FAMILLE", length = 10)
	public String getCodeFamille() {
		return this.codeFamille;
	}

	public void setCodeFamille(String codeFamille) {
		this.codeFamille = codeFamille;
	}

	@Column(name = "LIB_FAMILLE", length = 25)
	public String getLibFamille() {
		return this.libFamille;
	}

	public void setLibFamille(String libFamille) {
		this.libFamille = libFamille;
	}

	@Column(name = "DESCRIPTION_FAMILLE", length = 65535)
	public String getDescriptionFamille() {
		return this.descriptionFamille;
	}

	public void setDescriptionFamille(String descriptionFamille) {
		this.descriptionFamille = descriptionFamille;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "famille")
	public Set<Materiel> getMateriels() {
		return this.materiels;
	}

	public void setMateriels(Set<Materiel> materiels) {
		this.materiels = materiels;
	}

}
