package com.sati.model;
// Generated 18 mai 2022 à 07:58:28 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Fonction generated by hbm2java
 */
@Entity
@Table(name = "fonction", catalog = "ismistock_bd")
public class Fonction implements java.io.Serializable {

	private int idFonction;
	private String codeFonction;
	private String libFonction;
	private Set<Personne> personnes = new HashSet<Personne>(0);

	public Fonction() {
	}

	public Fonction(int idFonction) {
		this.idFonction = idFonction;
	}

	public Fonction(int idFonction, String codeFonction, String libFonction, Set<Personne> personnes) {
		this.idFonction = idFonction;
		this.codeFonction = codeFonction;
		this.libFonction = libFonction;
		this.personnes = personnes;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_FONCTION", unique = true, nullable = false)
	public int getIdFonction() {
		return this.idFonction;
	}

	public void setIdFonction(int idFonction) {
		this.idFonction = idFonction;
	}

	@Column(name = "CODE_FONCTION", length = 10)
	public String getCodeFonction() {
		return this.codeFonction;
	}

	public void setCodeFonction(String codeFonction) {
		this.codeFonction = codeFonction;
	}

	@Column(name = "LIB_FONCTION", length = 50)
	public String getLibFonction() {
		return this.libFonction;
	}

	public void setLibFonction(String libFonction) {
		this.libFonction = libFonction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fonction")
	public Set<Personne> getPersonnes() {
		return this.personnes;
	}

	public void setPersonnes(Set<Personne> personnes) {
		this.personnes = personnes;
	}

}
