package com.sati.model;
// Generated 4 mai 2023, 14:22:06 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Valeur generated by hbm2java
 */
@Entity
@Table(name = "valeur", catalog = "ismistock_bd")
public class Valeur implements java.io.Serializable {

	private Integer id;
	private Caracteristique caracteristique;
	private Materiel materiel;
	private String code;
	private String valeurCaracteristique;

	public Valeur() {
	}

	public Valeur(Caracteristique caracteristique, Materiel materiel) {
		this.caracteristique = caracteristique;
		this.materiel = materiel;
	}

	public Valeur(Caracteristique caracteristique, Materiel materiel, String code, String valeurCaracteristique) {
		this.caracteristique = caracteristique;
		this.materiel = materiel;
		this.code = code;
		this.valeurCaracteristique = valeurCaracteristique;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@GenericGenerator(name="lekerand" , strategy="increment")
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_CARACTERISTIQUE", nullable = false)
	public Caracteristique getCaracteristique() {
		return this.caracteristique;
	}

	public void setCaracteristique(Caracteristique caracteristique) {
		this.caracteristique = caracteristique;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_MATERIEL", nullable = false)
	public Materiel getMateriel() {
		return this.materiel;
	}

	public void setMateriel(Materiel materiel) {
		this.materiel = materiel;
	}

	@Column(name = "CODE", length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "VALEUR_CARACTERISTIQUE", length = 25)
	public String getValeurCaracteristique() {
		return this.valeurCaracteristique;
	}

	public void setValeurCaracteristique(String valeurCaracteristique) {
		this.valeurCaracteristique = valeurCaracteristique;
	}

}
